### ISSUE TITLE
GlobalObject Sync Fails and results in python errors

### ISSUE THREAD

**Issue by ajaytho** [ajaytho/mskaiagnt#1]
`./mskaiagnt sync-globalobj --srcmskengname xxxxxx01 --tgtmskengname xxxxxx02 -g --username xxxx --password xxxx --protocol https
Traceback (most recent call last):
  File "./mskaiagnt.py", line 627, in <module>
    cli()
  File "/u01/mskaiagnt/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/u01/mskaiagnt/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/u01/mskaiagnt/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/u01/mskaiagnt/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/u01/mskaiagnt/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/u01/mskaiagnt/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/u01/mskaiagnt/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
TypeError: sync_globalobj() missing 2 required positional arguments: 'srcenvname' and 'tgtenvname'`

**Comment by ajaytho** [comment]
Resolved in 1.1.0
